packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  lefthook: true

minimumReleaseAgeExclude:
  - lefthook-darwin-arm64@2.1.16
  - lefthook-darwin-x64@2.1.16
  - lefthook-freebsd-arm64@2.1.16
  - lefthook-freebsd-x64@2.1.16
  - lefthook-linux-arm64@2.1.16
  - lefthook-linux-x64@2.1.16
  - lefthook-openbsd-arm64@2.1.16
  - lefthook-openbsd-x64@2.1.16
  - lefthook-windows-arm64@2.1.16
  - lefthook-windows-x64@2.1.16
  - lefthook@2.1.16
  - '@ng-native/components@0.3.0'
  - '@ng-native/device@0.3.0'
  - '@ng-native/fabric@0.3.0'
  - '@ng-native/metro@0.3.0'
  - '@ng-native/platform@0.3.0'
  - '@ng-native/testing@0.3.0'
  - '@ng-native/expo@0.3.0'

saveExact: true
